# Two services: backend API on 5000 and frontend (nginx) on 80
version: '3.8'
services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '5000:5000'

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: http://host.docker.internal:5000/api
    container_name: frontend
    restart: always
    env_file:
      - ./client/.env
    ports:
      - '5173:5173'
